### ISSUE TITLE
Create protected route for image generation

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/starry#17]
The route for image generation should be protected, therefore only authenticated users with a valid cookie should be able to access it. 

Atm there's a draft boilerplate for authentication with Authkit, but it should be refactored to handle the protected route case. 

Refer to the Authkit repo as an example: https://github.com/workos/authkit

**Comment by yazaldefilimone** [comment]
Hello @LauraBeatris, are you doing it? Or can I try to do it?

**Comment by LauraBeatris** [comment]
Hey @yazaldefilimone! This has already landed on https://github.com/LauraBeatris/starry/commit/2a73896410a611bad1eb6ce0872275eb7a3fa2de
